
"use client"
import React, { useEffect } from 'react'
import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './css/globals.css'
import { ThemeProvider } from './components/theme-provider'
import ServiceWorkerRegister from './components/service-worker/ServiceWorkerRegister';
import toast, { Toaster } from 'react-hot-toast';
import { Provider } from 'react-redux';
import { store } from './store/store'








const dmSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-sans',
})

// export const metadata: Metadata = {
//   title: 'TailwindAdmin - Nextjs',
//   description: 'Generated by create next app',
// }




export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link rel='icon' href='/favicon.png' type='image/svg+xml' />
        {/* <link rel="manifest" href="/manifest.json" /> */}
        <meta name="theme-color" content="#5d87ff" />
      </head>
      <body className="">
        <Provider store={store}>
       
            {children}
            <Toaster />
            <ServiceWorkerRegister />

       
        </Provider>

      </body>
    </html>
  )
}
